workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: |
          cd $CM_BUILD_DIR
          flutter pub get
      - name: Build APK
        script: |
          cd $CM_BUILD_DIR
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
